name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Start selenoid
        run: |
          docker-compose up -d

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --system

      - name: Start selenoid
        run: |
          docker-compose up -d selenoid

      - name: Start selenoid-ui
        run: |
          docker-compose up -d selenoid-ui

      - name: Test with pytest
        run: |
          pytest

      - name: Clean up
        run: |
          docker-compose down
